name: 'airline_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des Seeds
seeds:
  airline_analytics:
    airports_coordinates:
      +column_types:
        airport_code: varchar(10)

# Configuration des Modèles
models:
  airline_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
      marketing:
        +tags: ["marketing"]
      operations:
        +tags: ["operations"]

# Configuration des Snapshots (Anticipation)
snapshots:
  airline_analytics:
    +target_schema: snapshots